/**
 * 
 *   //-- Create by J4BB3R<johanmaurel@gmail.com> --//
 *
 *   [Initial Date] : 08/12/2016
 *   [Last Date] : 09/12/2016
 *   [Description] :
 *      This class is the game view;
 *   [Increments] :
 *      - 09/12/2016 [v0.1] : Creation of the views;
 * 
 **/

package sudokufuzion.Views;

import sudokufuzion.Views.Components.GridMainPanel;
import sudokufuzion.Views.Components.GridCase;
import java.awt.Component;

public class mainView extends javax.swing.JFrame {

    // Panel Config
    private final static int LOCATION_X = 57, LOCATION_Y = 57;
    
    //====================//
    // Instance Attribute //
    //====================//
    
    private Component grid[][] = new Component[9][9];
    
    public mainView() {
        
        /////////////////////////////////
        //--Instanciation of the Grid--//
        /////////////////////////////////
        
        int X = 0, Y = 0, x = 0, y = 0, valTabY = 0, valTabX = 0;
        for(int i=0; i<9; i++){
            
            GridMainPanel buff = new GridMainPanel();
            X = LOCATION_X + buff.getWidth()*(i%3); // Calculate position of the containerGrid
            Y = LOCATION_Y + buff.getHeight()*(i/3); // Calculate position of the containerGrid
            buff.setLocation(X,Y);
            GridCase c = new GridCase();
            
            for (int z=0; z<9; z++) {
                
                valTabY = z/3 + 3*(i/3); // Calculate the index value into the tab
                valTabX = z%3 + 3*(i%3); // Calculate the index value into the tab
                
                GridCase caseBuff = new GridCase();
                caseBuff.setName("case["+valTabY+"]["+valTabX+"]");
                
                x = X + caseBuff.getWidth()*(z%3) + GridMainPanel.BORDER_SIZE; // Calculate position compare to the parentGrid relative position 
                y = Y + caseBuff.getHeight()*(z/3) + GridMainPanel.BORDER_SIZE; // Calculate position compare to the parentGrid relative position 
                
                caseBuff.setLocation(x,y); // Setting location
                this.add(caseBuff);
                
                grid[valTabY][valTabX] =(Component) caseBuff; // Component is save into the matrix;
            }
            
            this.add(buff);
        }
        
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUDOKU FUZION");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));

        panel.setBackground(new java.awt.Color(40, 40, 40));
        panel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelKeyPressed
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_panelKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
